apiVersion: v1
kind: Service
metadata:
    name: "implementasikubernetes-33b1"
    labels:
        app: "implementasikubernetes-33b1"
spec:
    type: LoadBalancer
    ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: http
    selector:
        app: "implementasikubernetes-33b1"